import { Question } from './types'

// ─────────────────────────────────────────────────────────────────────────────
// 20 interview questions for the Voice/Phone system type.
//
// Each question extracts a specific structural component of the system.
// The "why" teaches system design discipline. The "failure" anchors it in
// real production cost so the operator knows this isn't abstract theory.
// ─────────────────────────────────────────────────────────────────────────────

export const VOICE_PHONE_QUESTIONS: Question[] = [
  {
    id: 'trigger',
    number: 1,
    text: 'What starts this? Describe the exact moment when this system kicks off.',
    why: 'The trigger determines everything downstream — timing, actors, preconditions. Without a precise trigger definition, the system starts for the wrong reasons or not at all.',
    failure: 'A scheduling system was set to trigger on "any call." After-hours calls from existing patients bypassed intake entirely — no record created, no callback queued.',
    placeholder: 'e.g. Someone calls the main phone number and the line rings',
    mapsTo: 'trigger',
  },
  {
    id: 'primary_actor',
    number: 2,
    text: 'Who is on the other end? Describe the person this system is built to serve.',
    why: 'Actor definition shapes every decision gate. A new patient needs intake. A returning patient needs lookup. Confuse the two and you build the wrong flow for both.',
    failure: 'A voice agent assumed every caller was a new patient and ran full intake — existing patients had to re-give their name, DOB, and insurance every call. 34% abandoned.',
    placeholder: 'e.g. A new or returning patient wanting to schedule or reschedule an appointment',
    mapsTo: 'actor',
  },
  {
    id: 'success_output',
    number: 3,
    text: 'When this works perfectly, what does the person have that they didn\'t have before?',
    why: 'The success state IS the spec. If you cannot state the output precisely, neither can the system you\'re building. Vague success criteria produce vague systems.',
    placeholder: 'e.g. A confirmed appointment with a date, time, provider name, and SMS confirmation',
    mapsTo: 'output',
  },
  {
    id: 'preconditions',
    number: 4,
    text: 'What must already be true before this system can run? List every assumption.',
    why: 'Preconditions are the most-skipped section in system design and the most expensive to miss. Every assumption that isn\'t written down becomes a production crash.',
    failure: 'IB365 had 558 calls fail in one week. Root cause: a booking tool assumed the service record existed and was active. It wasn\'t. No precondition check. $2,100 in lost bookings.',
    placeholder: 'e.g. Patient record exists in database, service is active, provider has availability',
    isMultiline: true,
    mapsTo: 'precondition',
  },
  {
    id: 'precondition_failure',
    number: 5,
    text: 'Walk through what happens when any one of those assumptions fails.',
    why: 'Every precondition needs an explicit failure path. Silence is not a path — it\'s a silent error that looks like a success until a customer complains three days later.',
    failure: 'A tool returned {} (empty success) when the patient wasn\'t found. The caller heard "great, you\'re all set" and nothing was booked.',
    placeholder: 'e.g. Patient not found → create new record and continue intake; Service inactive → list available services and ask to clarify',
    isMultiline: true,
    mapsTo: 'error',
  },
  {
    id: 'secondary_actors',
    number: 6,
    text: 'Who else needs to know this happened? List everyone who gets notified.',
    why: 'Notification gaps mean staff act on stale information. The office manager needs to know a new patient booked. The patient needs confirmation. Define the notification chain now, not when the first gap causes a missed appointment.',
    placeholder: 'e.g. Office manager via SMS alert, patient via SMS confirmation, front desk via CRM notification',
    isMultiline: true,
    mapsTo: 'output',
  },
  {
    id: 'main_decision',
    number: 7,
    text: 'What\'s the main YES/NO fork in this process? Where does the path split?',
    why: 'Every business process has a critical decision gate. Undefined forks become the most expensive support calls — the system took a path no one designed.',
    placeholder: 'e.g. Is the patient new or returning? Does an available appointment exist this week?',
    mapsTo: 'decision',
  },
  {
    id: 'yes_path',
    number: 8,
    text: 'When the answer is YES — what does the system do next?',
    why: 'The happy path needs to be as explicitly designed as the error path. "It just works" is not a spec. Name every action.',
    placeholder: 'e.g. Look up their record, confirm details, offer available times, book appointment, send confirmation',
    isMultiline: true,
    mapsTo: 'output',
  },
  {
    id: 'no_path',
    number: 9,
    text: 'When the answer is NO — what does the system do instead?',
    why: '30% of voice appointment failures came from missing NO-path logic. Service not found → silent failure instead of asking to clarify. Define it before it costs you.',
    failure: 'Agent received "medication management" as service name. Backend expected UUID. No fuzzy match. 197 errors. Fix: 3 lines of code. Time to find it: 3 weeks.',
    placeholder: 'e.g. No availability this week → offer next available date, add to waitlist, log the intent in CRM',
    isMultiline: true,
    mapsTo: 'error',
  },
  {
    id: 'integrations',
    number: 10,
    text: 'What external systems does this touch? List every API, database, and third-party tool.',
    why: 'Every integration is an independent failure point. If you don\'t name them, you can\'t monitor them. When one goes down, you won\'t know which one.',
    placeholder: 'e.g. ElevenLabs (voice AI), PostgreSQL (patient records), Twilio (SMS), Stripe (billing)',
    isMultiline: true,
    mapsTo: 'integration',
  },
  {
    id: 'data_collection',
    number: 11,
    text: 'What data does this process need to collect, and where does it store it?',
    why: 'Data collection without a defined storage destination = data that disappears. Name the table and column before you build the form.',
    failure: 'A voice intake collected patient insurance information but passed it as a string to the note field instead of structured columns. Useless for billing. Re-collected every call.',
    placeholder: 'e.g. Patient name + DOB → leads table; appointment time + service → appointments table; insurance info → insurance_records table',
    isMultiline: true,
    mapsTo: 'data',
  },
  {
    id: 'health_metric',
    number: 12,
    text: 'What\'s the one number that would tell you this system is healthy vs broken?',
    why: 'Without a defined health metric, you rely on customer complaints instead of instruments. Pick the number that, if it dropped, you\'d know something was wrong.',
    placeholder: 'e.g. Appointment booking success rate >95%. Alert if it drops below 80% over 50 consecutive calls.',
    mapsTo: 'monitoring',
  },
  {
    id: 'silent_failure',
    number: 13,
    text: 'Describe the worst silent failure — the one where everything looks fine but it isn\'t.',
    why: 'Silent failures are the most expensive. A tool returning {} instead of an error still counts as "success" to the orchestrator. Define it so you can detect it.',
    failure: 'An appointment was booked in the DB but the SMS confirmation never fired. Patient thought it failed, called back, booked again. Staff had two patients for one slot.',
    placeholder: 'e.g. Appointment booked but SMS fails silently — patient never gets confirmation, shows up uncertain or not at all',
    mapsTo: 'error',
  },
  {
    id: 'time_gate',
    number: 14,
    text: 'Are there time windows, schedules, or conditions that change how this system behaves?',
    why: 'Time-based logic is the most commonly forgotten gate. After-hours, holidays, timezone differences — invisible until a patient calls at 9pm and nothing works.',
    placeholder: 'e.g. 8am–6pm PST → agent answers and books; after 6pm → voicemail with callback promise; holidays → closed message',
    mapsTo: 'decision',
  },
  {
    id: 'abandonment',
    number: 15,
    text: 'What should happen when the person disconnects or gives up before finishing?',
    why: 'Abandonment is a valid end state with its own logic. Without a defined path, incomplete sessions create orphaned records, missed callbacks, and confused patients.',
    placeholder: 'e.g. Save collected info, log as incomplete intent, trigger SMS follow-up in 30 minutes with a callback link',
    mapsTo: 'error',
  },
  {
    id: 'monitoring_gap',
    number: 16,
    text: 'If this system breaks completely and silently right now — how many minutes until you notice?',
    why: 'This is your monitoring SLA. The answer reveals whether your observability is instruments-based or complaint-based. The goal is minutes, not hours or days.',
    failure: 'IB365 ran 558 broken calls over 7 days before anyone noticed. Monitoring gap: ~10,000 minutes. Every answer above "15 minutes" is a monitoring debt.',
    placeholder: 'e.g. We\'d notice in ~30 minutes because the daily booking count dashboard would show a cliff',
    mapsTo: 'monitoring',
  },
  {
    id: 'constraints',
    number: 17,
    text: 'What\'s one thing this system must NEVER do, even if asked?',
    why: 'Negative constraints prevent the most expensive failures. Define them before the edge case happens at 2am.',
    placeholder: 'e.g. Never book an appointment without confirming patient name and DOB. Never skip the availability check.',
    mapsTo: 'error',
  },
  {
    id: 'escalation',
    number: 18,
    text: 'What would a human staff member do in a situation this system can\'t handle?',
    why: 'Every AI system needs a defined human escalation path. No escalation = customer stuck in a loop. Staff can\'t intervene if there\'s no handoff defined.',
    placeholder: 'e.g. Transfer to office manager, send "needs human review" notification to front desk, log full conversation context',
    mapsTo: 'output',
  },
  {
    id: 'system_name',
    number: 19,
    text: 'What are you calling this system? Give it a name.',
    why: 'Named systems get maintained. Unnamed systems get abandoned. The name anchors ownership — when something breaks, someone knows this is theirs.',
    placeholder: 'e.g. After-Hours Patient Intake, Scheduling Voice Agent, New Client Phone Onboarding',
  },
  {
    id: 'system_summary',
    number: 20,
    text: 'One sentence — what does this system do, for whom, and why it matters?',
    why: 'This becomes the first line of every spec, runbook, and onboarding doc. Any engineer, LLM, or new hire should read it and immediately understand what they\'re maintaining.',
    placeholder: 'e.g. Routes after-hours patient calls to an AI that books appointments or takes messages, so no new patient ever goes unanswered after 6pm',
  },
]
